name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.2'] #['8.1', '8.2']
        alpine-version: ['3.17'] #['3.16', '3.17']
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
#    - name: Login to GHCR
#      if: github.event_name != 'pull_request'
#      uses: docker/login-action@v2
#      with:
#        registry: ghcr.io
#        username: ${{ github.repository_owner }}
#        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        file: ./Dockerfile
        platforms: |
          linux/amd64
          linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        build-args: |
          "PHP_VERSION=${{ matrix.php-version }}"
          "ALPINE_VERSION=${{ matrix.alpine-version }}"
        labels: |
          org.opencontainers.image.source='https://github.com/TrucksNL/php-fpm'
          org.opencontainers.image.url='https://github.com/TrucksNL/php-fpm'
          org.label-schema.vcs-url='https://github.com/TrucksNL/php-fpm'
        tags: |
          trucksnl/php-fpm:${{ matrix.php-version }}-alpine${{ matrix.alpine-version }}-v${{ github.run_number }}
          trucksnl/php-fpm:${{ matrix.php-version }}-alpine${{ matrix.alpine-version }}
#          ghcr.io/trucksnl/php-fpm:${{ matrix.php-version }}-alpine${{ matrix.alpine-version }}
#          ghcr.io/trucksnl/php-fpm:${{ matrix.php-version }}-alpine${{ matrix.alpine-version }}-${{ github.run_number }}
